base_url = "https://tobeto.com/giris"
email_xpath = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/input[1]"
password_xpath = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/input[2]"
login_button_xpath = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
reviewsxpath = "//div[@id='__next']//nav//ul[@class='d-none d-xxl-flex navbar-nav']/li[3]/a[@href='#']"
systemMessagexpath = "//*[@id='__next']/div/main/section[1]/div/div[2]/div"
beginxpath = "/html//div[@id='__next']/div[@class='back-white']/main/section[2]//a[@href='#']"
beginTestxpath = "/html//div[@id='__next']/div[@class='back-white']//section[@class='bg-light py-2']//a[@href='/profilim/degerlendirmeler/tobeto-iste-basari-modeli/1']"
buttonClickxpath = "/html//div[@id='__next']/div[@class='back-white']//section[@class='bg-light py-2']//div[@class='row']//table[@class='table tbt-table']/tbody/tr[1]/td[2]/input[@name='318996']"
buttonClickxpath1 = "/html//div[@id='__next']/div[@class='back-white']//section[@class='bg-light py-2']//div[@class='row']//table[@class='table tbt-table']/tbody/tr[2]/td[3]/input[@name='318997']"
buttonClickxpath2 = "/html//div[@id='__next']/div[@class='back-white']//section[@class='bg-light py-2']//div[@class='row']//table[@class='table tbt-table']/tbody/tr[3]/td[4]/input[@name='318998']"
buttonClickxpath3 = "/html//div[@id='__next']/div[@class='back-white']//section[@class='bg-light py-2']//div[@class='row']//table[@class='table tbt-table']/tbody/tr[4]/td[5]/input[@name='318999']"
buttonClickxpath4 = "/html//div[@id='__next']/div[@class='back-white']//section[@class='bg-light py-2']//div[@class='row']//table[@class='table tbt-table']/tbody/tr[5]/td[5]/input[@name='319000']"
buttonClickxpath5 = "/html//div[@id='__next']/div[@class='back-white']//section[@class='bg-light py-2']//div[@class='row']//table[@class='table tbt-table']/tbody/tr[6]/td[3]/input[@name='319001']"
buttonClickxpath6 = "/html//div[@id='__next']/div[@class='back-white']//section[@class='bg-light py-2']//div[@class='row']//table[@class='table tbt-table']/tbody/tr[7]/td[5]/input[@name='319002']"